services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    restart:
      always
  dqt:
    image: couchdb:latest
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    depends_on:
      - web
    restart:
      always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - loris-site:/var/www/loris
      - loris-opt:/opt/loris/
      - loris-data:/data/loris/
    restart:
      always

volumes:
  mysql-data:
  loris-site:
  loris-opt:
  loris-data: