services:
  db:
    image: mysql:5.7
    env_file:
      - mysql.env
    restart:
      always
  dqt:
    image: couchdb:latest
    env_file:
      - couchdb.env
    restart:
      always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    restart:
      always