services:
  db:
    image: mysql:5.7
    volumes:
      - data-volume:/var/lib/db
    env_file:
      - mysql.env
    restart:
      always
  dqt:
    image: couchdb:latest
    ports:
      - "5984:5984"
    env_file:
      - couchdb.env
    restart:
      always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - data-volume:/var/lib/loris
    restart:
      always

volumes:
  data-volume: